/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class JFrameAutomoviles extends javax.swing.JFrame {

    /**
     * Creates new form JFrameAutomoviles
     */
    public JFrameAutomoviles() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel_Automoviles = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Automoviles = new javax.swing.JTable();
        jLabel_Marca = new javax.swing.JLabel();
        jComboBox_Marca = new javax.swing.JComboBox<>();
        jLabel_Modelo = new javax.swing.JLabel();
        jTextField_Modelo = new javax.swing.JTextField();
        jLabel_Anno = new javax.swing.JLabel();
        jFormattedTextField_Anno = new javax.swing.JFormattedTextField();
        jSpinner_Cilindraje = new javax.swing.JSpinner();
        jLabel_Cilindraje = new javax.swing.JLabel();
        jSpinner_CantidadAsientos = new javax.swing.JSpinner();
        jLabel_CantidadAsientos = new javax.swing.JLabel();
        jLabel_Placa = new javax.swing.JLabel();
        jTextField_Placa = new javax.swing.JTextField();
        jButton_Ingresar = new javax.swing.JButton();
        jButton_Actualizar = new javax.swing.JButton();
        jButton_Eliminar = new javax.swing.JButton();
        jButton_Limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_Automoviles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Modelo", "Cilindraje", "Cantidad de Asientos", "Placa", "Año"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Automoviles.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable_Automoviles);
        if (jTable_Automoviles.getColumnModel().getColumnCount() > 0) {
            jTable_Automoviles.getColumnModel().getColumn(0).setResizable(false);
            jTable_Automoviles.getColumnModel().getColumn(1).setResizable(false);
            jTable_Automoviles.getColumnModel().getColumn(2).setResizable(false);
            jTable_Automoviles.getColumnModel().getColumn(3).setResizable(false);
            jTable_Automoviles.getColumnModel().getColumn(4).setResizable(false);
            jTable_Automoviles.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel_Marca.setText("Marca");

        jComboBox_Marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Audi", "Chevrolet", "Honda", "Hyundai", "Kia", "Nissan", "Ford", "Suzuki", "Toyota" }));
        jComboBox_Marca.setSelectedIndex(8);
        jComboBox_Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_MarcaActionPerformed(evt);
            }
        });

        jLabel_Modelo.setText("Modelo");

        jTextField_Modelo.setToolTipText("");

        jLabel_Anno.setText("Año");
        jLabel_Anno.setToolTipText("");

        try {
            jFormattedTextField_Anno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel_Cilindraje.setText("Cilindraje");

        jLabel_CantidadAsientos.setText("Cantidad de Asientos");

        jLabel_Placa.setText("Placa");

        jButton_Ingresar.setText("Ingresar");

        jButton_Actualizar.setText("Actualizar");

        jButton_Eliminar.setText("Eliminar");

        jButton_Limpiar.setText("Limpiar");

        javax.swing.GroupLayout jPanel_AutomovilesLayout = new javax.swing.GroupLayout(jPanel_Automoviles);
        jPanel_Automoviles.setLayout(jPanel_AutomovilesLayout);
        jPanel_AutomovilesLayout.setHorizontalGroup(
            jPanel_AutomovilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AutomovilesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_AutomovilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_AutomovilesLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel_AutomovilesLayout.createSequentialGroup()
                        .addGroup(jPanel_AutomovilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Marca)
                            .addComponent(jLabel_Modelo)
                            .addComponent(jLabel_Anno)
                            .addComponent(jLabel_Cilindraje)
                            .addComponent(jLabel_CantidadAsientos)
                            .addComponent(jLabel_Placa))
                        .addGap(112, 112, 112)
                        .addGroup(jPanel_AutomovilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSpinner_CantidadAsientos)
                            .addComponent(jSpinner_Cilindraje)
                            .addComponent(jTextField_Modelo)
                            .addComponent(jFormattedTextField_Anno)
                            .addComponent(jTextField_Placa)
                            .addComponent(jComboBox_Marca, 0, 250, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                        .addGroup(jPanel_AutomovilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_Actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Ingresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(150, 150, 150))))
        );
        jPanel_AutomovilesLayout.setVerticalGroup(
            jPanel_AutomovilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AutomovilesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel_AutomovilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Marca)
                    .addComponent(jComboBox_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Ingresar))
                .addGap(18, 18, 18)
                .addGroup(jPanel_AutomovilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Modelo)
                    .addComponent(jTextField_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Actualizar))
                .addGap(23, 23, 23)
                .addGroup(jPanel_AutomovilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Anno)
                    .addComponent(jFormattedTextField_Anno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Eliminar))
                .addGap(24, 24, 24)
                .addGroup(jPanel_AutomovilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner_Cilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Cilindraje)
                    .addComponent(jButton_Limpiar))
                .addGap(18, 18, 18)
                .addGroup(jPanel_AutomovilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner_CantidadAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_CantidadAsientos))
                .addGap(18, 18, 18)
                .addGroup(jPanel_AutomovilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Placa)
                    .addComponent(jTextField_Placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Automoviles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Automoviles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_MarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_MarcaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAutomoviles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAutomoviles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAutomoviles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAutomoviles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAutomoviles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton_Actualizar;
    private javax.swing.JButton jButton_Eliminar;
    private javax.swing.JButton jButton_Ingresar;
    private javax.swing.JButton jButton_Limpiar;
    private javax.swing.JComboBox<String> jComboBox_Marca;
    private javax.swing.JFormattedTextField jFormattedTextField_Anno;
    private javax.swing.JLabel jLabel_Anno;
    private javax.swing.JLabel jLabel_CantidadAsientos;
    private javax.swing.JLabel jLabel_Cilindraje;
    private javax.swing.JLabel jLabel_Marca;
    private javax.swing.JLabel jLabel_Modelo;
    private javax.swing.JLabel jLabel_Placa;
    private javax.swing.JPanel jPanel_Automoviles;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner_CantidadAsientos;
    private javax.swing.JSpinner jSpinner_Cilindraje;
    private javax.swing.JTable jTable_Automoviles;
    private javax.swing.JTextField jTextField_Modelo;
    private javax.swing.JTextField jTextField_Placa;
    // End of variables declaration//GEN-END:variables
}
